const imagePaths = {
    hero1:     'images/hero_run_01.png',
    hero2:     'images/hero_run_02.png',
    hero3:     'images/hero_run_03.png',
    hero4:     'images/hero_run_04.png',
    floor1:    'images/floor_01.png',
    floor2:    'images/floor_02.png',
    floor3:    'images/floor_03.png',
    floor4:    'images/floor_04.png',
    floor5:    'images/floor_05.png',
    floor6:    'images/floor_06.png',
    tree1:     'images/tree_01.png',
    tree2:     'images/tree_02.png',
    tree3:     'images/tree_03.png',
    tree4:     'images/tree_04.png',
    tree5:     'images/tree_05.png',
    grass1:    'images/grass_01.png',
    grass2:    'images/grass_02.png',
    grass3:    'images/grass_03.png',
    rocks1:    'images/rocks_01.png',
    mountain1: 'images/mountain_01.png',
    mountain2: 'images/mountain_02.png',
    mountain3: 'images/mountain_03.png',
    mountain4: 'images/mountain_04.png',
    mountain5: 'images/mountain_05.png',
    mountain6: 'images/mountain_06.png',
    tech1:     'images/tech_01.png',
    tech2:     'images/tech_02.png',
    tech3:     'images/tech_03.png',
    tech4:     'images/tech_04.png',
    tech5:     'images/tech_05.png',
    tech6:     'images/tech_06.png',
    tech7:     'images/tech_07.png'
}

export default imagePaths